name: marvel_comics_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.1
  carousel_slider: 3.0.0
  crypto: 3.0.0
  cupertino_icons: 1.0.2
  dio: 3.0.10
  flutter_modular: 3.0.1
  flutter_platform_widgets: ^0.80.0
  getwidget: ^1.2.4
  json_annotation: 3.1.1
  retrofit: 1.3.4+1
  rx_notifier: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.5
  json_serializable: 3.5.1
  retrofit_generator: 1.4.1+3
flutter:
  uses-material-design: true
